#!/bin/sh
exec java \
  -Dloader.main=com.binaryscan.javachecker.health.HealthcheckMain \
  -cp /opt/binaryscan/java-checker/java-checker.jar \
  org.springframework.boot.loader.launch.PropertiesLauncher
