#!/bin/sh

set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
# shellcheck disable=SC1091
. "$SCRIPT_DIR/lib.sh"

require_command docker
load_settings
verify_image "$BINARYSCAN_BUILDER_IMAGE" ""
verify_image "$BINARYSCAN_MYSQL_IMAGE" ""
verify_image "$BINARYSCAN_TRIVY_RUNTIME_DB_IMAGE" ""
verify_image "$BINARYSCAN_ARCHIVE_TOOLS_IMAGE" ""
verify_image "$BINARYSCAN_JAVA_RUNTIME_IMAGE" ""
verify_image "$BINARYSCAN_GHIDRA_RUNTIME_IMAGE" ""
verify_image "$BINARYSCAN_C_CHECKER_BUILDER_IMAGE" ""
verify_image "$BINARYSCAN_JAVA_CHECKER_BUILDER_IMAGE" ""
verify_image "$BINARYSCAN_C_CHECKER_JRE_IMAGE" ""

image_id() {
	docker image inspect "$1" --format '{{.Id}}' 2>/dev/null ||
		fail "required image is not loaded: $1"
}

temporary="$PROJECT_ROOT/images.lock.env.tmp"
cat >"$temporary" <<EOF
# Frozen external images required for a network-isolated source build.
BINARYSCAN_PLATFORM=$BINARYSCAN_PLATFORM
BINARYSCAN_BUILDER_IMAGE=$BINARYSCAN_BUILDER_IMAGE
BINARYSCAN_BUILDER_IMAGE_ID=$(image_id "$BINARYSCAN_BUILDER_IMAGE")
BINARYSCAN_MYSQL_IMAGE=$BINARYSCAN_MYSQL_IMAGE
BINARYSCAN_MYSQL_IMAGE_ID=$(image_id "$BINARYSCAN_MYSQL_IMAGE")
BINARYSCAN_TRIVY_RUNTIME_DB_IMAGE=$BINARYSCAN_TRIVY_RUNTIME_DB_IMAGE
BINARYSCAN_TRIVY_RUNTIME_DB_IMAGE_ID=$(image_id "$BINARYSCAN_TRIVY_RUNTIME_DB_IMAGE")
BINARYSCAN_ARCHIVE_TOOLS_IMAGE=$BINARYSCAN_ARCHIVE_TOOLS_IMAGE
BINARYSCAN_ARCHIVE_TOOLS_IMAGE_ID=$(image_id "$BINARYSCAN_ARCHIVE_TOOLS_IMAGE")
BINARYSCAN_JAVA_RUNTIME_IMAGE=$BINARYSCAN_JAVA_RUNTIME_IMAGE
BINARYSCAN_JAVA_RUNTIME_IMAGE_ID=$(image_id "$BINARYSCAN_JAVA_RUNTIME_IMAGE")
BINARYSCAN_GHIDRA_RUNTIME_IMAGE=$BINARYSCAN_GHIDRA_RUNTIME_IMAGE
BINARYSCAN_GHIDRA_RUNTIME_IMAGE_ID=$(image_id "$BINARYSCAN_GHIDRA_RUNTIME_IMAGE")
BINARYSCAN_C_CHECKER_BUILDER_IMAGE=$BINARYSCAN_C_CHECKER_BUILDER_IMAGE
BINARYSCAN_C_CHECKER_BUILDER_IMAGE_ID=$(image_id "$BINARYSCAN_C_CHECKER_BUILDER_IMAGE")
BINARYSCAN_JAVA_CHECKER_BUILDER_IMAGE=$BINARYSCAN_JAVA_CHECKER_BUILDER_IMAGE
BINARYSCAN_JAVA_CHECKER_BUILDER_IMAGE_ID=$(image_id "$BINARYSCAN_JAVA_CHECKER_BUILDER_IMAGE")
BINARYSCAN_C_CHECKER_JRE_IMAGE=$BINARYSCAN_C_CHECKER_JRE_IMAGE
BINARYSCAN_C_CHECKER_JRE_IMAGE_ID=$(image_id "$BINARYSCAN_C_CHECKER_JRE_IMAGE")
EOF
mv "$temporary" "$PROJECT_ROOT/images.lock.env"
note "images.lock.env now contains immutable local image IDs"
note "review and commit it before creating the source ZIP"
